# Generated by Django 6.0.6 on 2026-06-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cubeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_id', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('?', 'Unknown')], default='?', max_length=1)),
                ('wca_year', models.IntegerField()),
                ('competition_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('has_avg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_id', models.CharField(max_length=10, unique=True)),
                ('pseudo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CubeurNationalityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_until', models.IntegerField(blank=True, null=True)),
                ('cubeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cubeur')),
            ],
            options={
                'verbose_name': 'Exception de nationalité',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('day_count', models.IntegerField()),
                ('participant_count', models.IntegerField(default=-1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_championship', models.BooleanField(default=False)),
                ('organizers', models.JSONField(default=list)),
                ('delegates', models.JSONField(default=list)),
                ('events', models.ManyToManyField(to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='CubeurRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('single', 'Single'), ('average', 'Average')])),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('cubeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='core.cubeur')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'unique_together': {('cubeur', 'event', 'result_type')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('score', models.IntegerField(default=-1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('cubeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cubeur')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'unique_together': {('competition', 'cubeur', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('user', 'game', 'date')},
            },
        ),
    ]
