# Generated by Django 6.0.6 on 2026-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championshipresult',
            old_name='score',
            new_name='average',
        ),
        migrations.AddField(
            model_name='championshipresult',
            name='best',
            field=models.IntegerField(default=-1),
        ),
    ]
