# Generated by Django 6.0.6 on 2026-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_score_championshipresult_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date_from',
            field=models.DateField(null=True),
        ),
    ]
