# Generated by Django 6.0.6 on 2026-06-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_competition_date_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('ranking_result_type', models.CharField(default='average', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cubeur',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cubeurranking',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddIndex(
            model_name='championshipresult',
            index=models.Index(fields=['competition', 'event'], name='core_champi_competi_e41073_idx'),
        ),
        migrations.AddIndex(
            model_name='cubeurranking',
            index=models.Index(fields=['cubeur', 'event', 'result_type'], name='core_cubeur_cubeur__73eca8_idx'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_competition', to='core.competition'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='cubeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_cubeur', to='core.cubeur'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='location_competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_location', to='core.competition'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='podium_competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_podium', to='core.competition'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='podium_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_podium_event', to='core.event'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='ranking_cubeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_ranking', to='core.cubeur'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='ranking_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
    ]
