# Generated by Django 6.0.6 on 2026-07-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailychallenge_cubeur_avatar_url_cubeurranking_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cubeur_guesses', models.JSONField(default=list)),
                ('compet_guesses', models.JSONField(default=list)),
                ('ranking_guesses', models.JSONField(default=list)),
                ('podium_guesses', models.JSONField(default=list)),
                ('location_guess', models.JSONField(default=dict)),
                ('cubeur_done', models.BooleanField(default=False)),
                ('compet_done', models.BooleanField(default=False)),
                ('ranking_done', models.BooleanField(default=False)),
                ('podium_done', models.BooleanField(default=False)),
                ('location_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='core_dailyp_user_id_ea770e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
