# Generated by Django 6.0.6 on 2026-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pseudo',
            field=models.CharField(max_length=30),
        ),
    ]
