# Generated by Django 6.0.6 on 2026-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='compet_latest_hint',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='cubeur_latest_hint',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='podium_latest_hint',
            field=models.JSONField(default=dict),
        ),
    ]
